### ISSUE TITLE
Clarify unreal engine support

### ISSUE THREAD

**Issue by anb** [ViveSoftware/ViveFoveatedRendering#7]
Following links from Vive forum regarding foveated rendering mostly fails 404 because of the company namespace changed from ViveSF to ViveSoftware. Also, it seems unreal support has been quietly dropped.

It would be nice to clarify the Unreal 4 support status. Thanks !

**Comment by ViveSW** [comment]
Hi anb, the UE4 version of ViveFoveatedRenderingPlugin is under the GitHub account ViveSW, since it's forked from a private repository of Epic Games, you will have to link your Epic Games account to GitHub account and get authorized by Epic Games to access the content. There's an official page addressing this: https://www.unrealengine.com/en-US/ue4-on-github

**Comment by anb** [comment]
Ok, thanks for the information !
